### ISSUE TITLE
Chunks don't decrease when TPS drops

### ISSUE THREAD

**Issue by MrTalon63** [froobynooby/ViewDistanceTweaks#1]
I have this plugin on the newest 1.15.2 paper server. And when TPS drops below 19.5 chunks don't decrease even after 40 seconds.
Here's my config file: https://pastebin.com/wgmtQ4VC

Maybe I'm doing something wrong, idk.

**Comment by froobynooby** [comment]
I've tried your config locally and I was able to see the view distance decreasing when the TPS dropped. If you mean the actual number of loaded chunks is not decreasing then this is to be expected since you have no-tick view distance, so the plugin is essentially only decreasing the number of chunks that are ticking

**Comment by MrTalon63** [comment]
https://i.imgur.com/HOtmKli.png TPS dropped below 18, and still, VDT didn't do anything

**Comment by froobynooby** [comment]
I suspect what is happening there is that your TPS is low because there is some task running every so often that is taking a very long time to complete. VDT will ignore these rare large lag spikes when it calculates TPS, so as far as the plugin is concerned the TPS is still normal. If you can attach a timings report I could confirm this

If you want to disable this behaviour you can set `tps-tracker-settings > trim-outliers-to-within` to a very high value, like 1000000

**Comment by MrTalon63** [comment]
Setting this value to 1000000 worked! Also here are my timings https://timings.aikar.co/?id=ea4ea34245dd4641a0af0c96eef88d29

**Comment by froobynooby** [comment]
Timings seem to confirm that's what is happening - the odd tick taking much longer than it should. Glad it's working for you with that new value!
