### ISSUE TITLE
Chunks flickering when the view distance changes on latest PaperMC

### ISSUE THREAD

**Issue by HenrikoMagnifico** [froobynooby/ViewDistanceTweaks#25]
I've noticed that on the latest version of PaperMC (205-1.18.1) chunks have started to flicker whenever the view distance changes through view distance tweaks, which is quite annoying and makes the plugin almost unusable. Please look into this issue, thank you!

**Comment by froobynooby** [comment]
The flickering is an unfortunate consequence of the new way fog works in 1.18. In order to stop it the plugin needs to trick the client into thinking the server's view distance isn't actually changing. This is a bit harder to do with Paper's chunk system because it (correctly) sends the client the updated view distance whenever it is changed.

If anyone wants to test a Paper compatible version plugin [ViewDistanceTweaks.zip](https://github.com/froobynooby/ViewDistanceTweaks/files/8116572/ViewDistanceTweaks.zip) before I upload it to Spigot, it would be much appreciated

**Comment by Ceddix** [comment]
Since the constant reloading is a bit annoying for our players, I will definitely test it :)
Is there anything I should look out for?
