### ISSUE TITLE
Looks like it won't go below 2!

### ISSUE THREAD

**Issue by iperrealistico** [froobynooby/ViewDistanceTweaks#9]
Hey! Awesome plugin here I must say :)
Only issue I noticed so far is that no-tick-view-distance won't go under value 2 if i configure it to be min 0 max 1 or min 1 max 1 or min 0 max 0. I want it to be 1 or entirely disabled for specific worlds when there are many chunks loaded.

Same for regular view distance! It won't go under 2. For example in the end I wanted it to be litterally the lowest possible value, 1.

![image](https://user-images.githubusercontent.com/25549272/102205405-7197f780-3ecb-11eb-906d-01bae9a1f889.png)

Tuinity version git-Tuinity-"cc34294" (MC: 1.16.4)
ViewDistanceTweaks version 1.3.1

**Comment by froobynooby** [comment]
Hey, glad you like the plugin!

It's not actually possible to set the view distance of the server below 2 at the moment. Even if you set it to 1 in server.properties it will bump it up to 2

It's the same for no-tick view distance, it can't be set lower than 2. I think you might be misunderstanding how no-tick view distance works, though, because it's a bit confusing. As an example of how it works: if your view distance is 4 and your no-tick view distance is 8 then you will be able to see 8 chunks out, but only those out to a distance of 4 will be ticking.

There's no nice way to disable no-tick view distance in a specific world with the plugin at the moment, but I will likely add this in the future. In the mean time, setting a world's no-tick view distance to be 2 at max will effectively disable it for that world

**Comment by iperrealistico** [comment]
Yeah, since both view distance and no tick view distance are 2 it would be technically disabled 👍 
Would be awesome if paper implemented view-distance = 1, could it be dangerous/break stuff?

**Comment by froobynooby** [comment]
I'm not too sure about the reasoning for having 2 as the minimum, but I would have thought if it was possible to have it as 1 then it would probably already be in Paper. Might be a limitation of the client? Would probably need to ask the Paper devs for the reasoning / if it is possible
